<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>LedgerLeaf Analytics Report</title>
    <style>
        body {
            font-family: 'Inter', 'Segoe UI', sans-serif;
            background: #ffffff;
            color: #1a1a1a;
            padding: 40px;
            font-size: 14px;
            line-height: 1.6;
        }
        .header {
            border-bottom: 3px solid #5CB85C;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 28px;
            font-weight: 300;
            color: #1a1a1a;
        }
        .logo span {
            color: #5CB85C;
            font-weight: 600;
        }
        .logo-sub {
            color: #6b7280;
            font-size: 14px;
            margin-top: 4px;
        }
        .section {
            margin-bottom: 30px;
        }
        .section-title {
            font-size: 18px;
            font-weight: 600;
            color: #1a1a1a;
            border-bottom: 2px solid #e5e5e5;
            padding-bottom: 8px;
            margin-bottom: 15px;
        }
        .grid-2 {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }
        .grid-4 {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr;
            gap: 15px;
        }
        .stat-card {
            background: #f9fafb;
            border-radius: 8px;
            padding: 15px;
            border: 1px solid #e5e5e5;
        }
        .stat-label {
            color: #6b7280;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 600;
        }
        .stat-value {
            font-size: 20px;
            font-weight: 700;
            margin-top: 4px;
        }
        .stat-value.green { color: #5CB85C; }
        .stat-value.red { color: #EF4444; }
        .stat-value.blue { color: #3B82F6; }
        .stat-value.orange { color: #F59E0B; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 13px;
        }
        th {
            background: #f3f4f6;
            text-align: left;
            padding: 10px 12px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: #6b7280;
            font-weight: 600;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e5e5;
        }
        .text-right { text-align: right; }
        .amount { font-weight: 600; }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e5e5;
            text-align: center;
            color: #9ca3af;
            font-size: 11px;
        }
        .badge {
            display: inline-block;
            padding: 2px 10px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 600;
        }
        .badge-completed {
            background: #d1fae5;
            color: #065f46;
        }
        .badge-in-progress {
            background: #dbeafe;
            color: #1e40af;
        }
        .print-break {
            page-break-after: always;
        }
        .total-row {
            font-weight: bold;
            border-top: 2px solid #e5e5e5;
        }
    </style>
</head>
<body>
    {{-- Header --}}
    <div class="header">
        <div class="logo">Ledger<span>Leaf</span></div>
        <div class="logo-sub">
            Analytics Report •
            {{ $generated_at ?? now()->format('F j, Y g:i A') }}
        </div>
    </div>

    {{-- Period --}}
    <div class="section">
        <h2 class="section-title">Report Period</h2>
        <p style="color: #4b5563;">
            {{ $period['start'] ?? 'N/A' }} - {{ $period['end'] ?? 'N/A' }}
        </p>
    </div>

    {{-- Content Section --}}
    @yield('content')

    {{-- Footer --}}
    <div class="footer">
        Generated by LedgerLeaf • {{ $generated_at ?? now()->format('F j, Y g:i A') }}
        <br>
        This report is automatically generated and contains your financial data.
    </div>
</body>
</html>